;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ergoemacs-command-loop--shift-translate
        indent-for-tab-command
        info
        set-rectangular-region-anchor
        ))

(setq mc/cmds-to-run-once
      '(
        ido-find-file
        ))
